[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "openai>=1.91.0",
    "requests>=2.32.4",
    "streamlit>=1.46.0",
]
